import type { TutorialStep } from '../../types/game'

/**
 * Tutorial steps that guide the player through all core mechanics
 */
export const tutorialSteps: TutorialStep[] = [
  {
    id: 'welcome',
    title: 'Welcome to Factory Bound!',
    description: 'Welcome to Factory Bound! In this game, you\'ll build an automated factory, defend against enemies, and research new technologies. Let\'s start with the basics.',
    position: 'center',
    objective: 'Click "Next" to continue',
  },
  {
    id: 'camera_controls',
    title: 'Camera Controls',
    description: 'Use WASD or Arrow keys to pan the camera around the map. Use the mouse wheel to zoom in and out. Try moving the camera now!',
    position: 'center',
    objective: 'Move the camera to explore',
  },
  {
    id: 'resources_intro',
    title: 'Understanding Resources',
    description: 'The map contains various resources like Iron Ore (⚙) and Copper Ore (🔩). These are essential for building your factory. Resources appear as colored patches on the ground.',
    target: '.resource-display',
    position: 'bottom',
    objective: 'Learn about resources',
  },
  {
    id: 'building_menu',
    title: 'Build Menu',
    description: 'Click the "Build" button to open the build menu. Here you can see all the machines you can construct. Each building requires specific materials.',
    target: '.quick-btn:nth-child(4)',
    position: 'bottom',
    objective: 'Open the build menu',
  },
  {
    id: 'place_miner',
    title: 'Placing Your First Miner',
    description: 'Miners extract resources from ore patches. Select a Miner from the build menu and place it on an ore patch. Miners will automatically extract resources over time.',
    position: 'center',
    objective: 'Place a miner on an ore patch',
  },
  {
    id: 'power_system',
    title: 'Power Infrastructure',
    description: 'Most machines require power to operate. Build a Power Plant to generate electricity. Power plants need to be connected to machines to provide power.',
    position: 'center',
    objective: 'Build a power plant',
  },
  {
    id: 'transport_belts',
    title: 'Transport Belts',
    description: 'Belts move items from one machine to another. Place belts to connect your miner to other machines. Belts automatically transport items in the direction they face.',
    position: 'center',
    objective: 'Place transport belts',
  },
  {
    id: 'inserters',
    title: 'Inserters',
    description: 'Inserters pick up items from one machine and place them in another. They\'re essential for automation! Place an inserter to transfer items between machines or belts.',
    position: 'center',
    objective: 'Place an inserter',
  },
  {
    id: 'assemblers',
    title: 'Assemblers and Crafting',
    description: 'Assemblers craft items using recipes. For example, Iron Ore can be smelted into Iron Plates. Select an assembler, place it, and assign it a recipe from its menu.',
    position: 'center',
    objective: 'Build an assembler',
  },
  {
    id: 'inventory',
    title: 'Inventory Management',
    description: 'Click the Inventory button to see your items. You can drag items to and from machines. Resources stack up to 100 items per slot.',
    target: '.quick-btn:nth-child(1)',
    position: 'bottom',
    objective: 'Open your inventory',
  },
  {
    id: 'tech_tree',
    title: 'Research and Technology',
    description: 'Click the Tech Tree button to see available technologies. Research unlocks new machines and recipes. Research requires Science Packs which you must produce.',
    target: '.quick-btn:nth-child(3)',
    position: 'bottom',
    objective: 'View the tech tree',
  },
  {
    id: 'enemies_intro',
    title: 'Enemy Threats',
    description: 'Enemies will periodically attack your base in waves. They target your machines and will destroy them if not defended. Prepare your defenses!',
    position: 'center',
    objective: 'Understand the enemy threat',
  },
  {
    id: 'turrets',
    title: 'Building Defenses',
    description: 'Turrets automatically shoot nearby enemies. Place turrets around your base perimeter. Remember to keep them supplied with ammunition!',
    position: 'center',
    objective: 'Build a turret',
  },
  {
    id: 'node_editor',
    title: 'Node-Based Programming',
    description: 'The Node Editor lets you program machine behavior! You can create logic to enable/disable machines based on conditions like inventory levels or power status.',
    target: '.quick-btn:nth-child(2)',
    position: 'bottom',
    objective: 'Learn about automation',
  },
  {
    id: 'save_game',
    title: 'Saving Your Progress',
    description: 'Click the settings button (⚙) to save your game. The game also auto-saves every 5 minutes. You can have multiple save files.',
    target: '.control-btn:nth-child(2)',
    position: 'left',
    objective: 'Learn to save',
  },
  {
    id: 'tutorial_complete',
    title: 'Tutorial Complete!',
    description: 'You\'ve learned the basics! Now it\'s time to build your factory empire. Remember: Automate everything, defend your base, and research new technologies. Good luck!',
    position: 'center',
    objective: 'Start playing!',
  },
]
